"""Render current and immutable historical Markdown. Never execute snapshot code."""

import argparse
import hashlib
import html
import json
import re
import shutil
import subprocess
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

import markdown
from packaging.version import Version

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "sites/dist"
BASE = "/python.tts.api.client"
REPO = "https://github.com/lambdawalker/python.tts.api.client"
PAGES = [
    "index",
    "installation",
    "quickstart",
    "concepts",
    "recipes",
    "api",
    "examples",
    "limitations",
    "troubleshooting",
    "migration",
]
LABELS = {
    "en": [
        "Overview",
        "Installation",
        "Quickstart",
        "Concepts",
        "Recipes",
        "API",
        "Examples",
        "Limitations",
        "Troubleshooting",
        "Migration",
    ],
    "es": [
        "Introducción",
        "Instalación",
        "Inicio rápido",
        "Conceptos",
        "Recetas",
        "API",
        "Ejemplos",
        "Limitaciones",
        "Problemas",
        "Migración",
    ],
}


def read(path, ref=None):
    if ref:
        if not re.fullmatch("[0-9a-f]{40}", ref):
            raise ValueError("Snapshot revision must be an immutable SHA")
        return subprocess.check_output(
            ["git", "show", f"{ref}:{path}"], cwd=ROOT, text=True
        )  # missing objects fail closed
    return (ROOT / path).read_text()


def catalog():
    records = [
        json.loads(p.read_text()) for p in sorted((ROOT / "docs/releases/history").glob("*.json"))
    ]
    for record in records:
        if record["module"] != "tts-api-client" or record["destination"] != "pypi":
            raise ValueError("Unsupported release module/destination")
        if not re.fullmatch(r"\d+\.\d+\.\d+", record["version"]):
            raise ValueError("Invalid release version")
        for field in ["source_sha", "docs_sha"]:
            if not re.fullmatch("[0-9a-f]{40}", record[field]):
                raise ValueError("Invalid immutable revision")
        if record["tag"] != "v" + record["version"] or not record["files"]:
            raise ValueError("Incomplete publication evidence")
    if len({r["version"] for r in records}) != len(records):
        raise ValueError("Conflicting release records")
    return sorted(records, key=lambda r: Version(r["version"]))


def installation(record=None, lang="en"):
    if record:
        coordinate = f"tts-api-client=={record['version']}"
        note = "Confirmed PyPI release." if lang == "en" else "Publicación confirmada en PyPI."
    else:
        coordinate = "tts-api-client @ git+" + REPO + ".git@main"
        note = (
            "Development source from the moving main branch."
            if lang == "en"
            else "Código de desarrollo de la rama main, que puede cambiar."
        )
    return (
        note
        + '\n\n```bash\nuv add "'
        + coordinate
        + '"\n'
        + 'python -m pip install "'
        + coordinate
        + '"\n```\n'
    )


def import_document():
    records = catalog()
    return (
        "<!-- Generated by scripts/docs.py build; edit docs/releases/history instead. -->\n"
        "# Installation / Instalación\n\n"
        + installation(records[-1] if records else None)
        + "\nPython >=3.10. Import: `tts_api_client`.\n\n"
        "See [consumer guides](docs/agents/index.md) for development scope.\n"
    )


def localized(page, lang, ref=None):
    canonical = read(f"docs/agents/{page}.md", ref)
    if lang == "en":
        return canonical, False
    try:
        manifest = json.loads(read("docs/translations.json", ref))
    except (FileNotFoundError, subprocess.CalledProcessError):
        return canonical, True
    expected = hashlib.sha256(canonical.encode()).hexdigest()
    item = manifest.get(page)
    if not item or item["canonical_sha256"] != expected:
        return canonical, True
    try:
        translated = read(f"docs/es/{page}.md", ref)
    except (FileNotFoundError, subprocess.CalledProcessError):
        return canonical, True
    if item["translation_sha256"] != hashlib.sha256(translated.encode()).hexdigest():
        return canonical, True
    return translated, False


def transform_links(text, version, lang, source_sha, raw):
    """Authored inline links only, excluding fenced code. Tested for fragments/URLs."""

    def rewrite(match):
        label, target = match.groups()
        if target.startswith(("https:", "http:", "#")):
            return match.group(0)
        path, sep, fragment = target.partition("#")
        if path.startswith("../../"):
            url = f"{REPO}/blob/{source_sha}/{path[6:]}"
        elif path.endswith(".md") and Path(path).stem in PAGES:
            slug = Path(path).stem
            url = (
                f"{BASE}/agents/{lang}/{version}/{slug}.md"
                if raw
                else f"{BASE}/{lang}/{version}/{slug}/"
            )
        else:
            raise ValueError(f"Unsupported authored link: {target}")
        return f"[{label}]({url}{sep}{fragment})"

    chunks = re.split(r"(```[\s\S]*?```)", text)
    return "".join(
        chunk if chunk.startswith("```") else re.sub(r"\[([^\]]+)\]\(([^\s)]+)\)", rewrite, chunk)
        for chunk in chunks
    )


def write(path, text):
    target = OUT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)


def build():
    shutil.rmtree(OUT, ignore_errors=True)
    OUT.mkdir(parents=True)
    for asset in ["style.css", "copy.js"]:
        shutil.copyfile(ROOT / "sites" / asset, OUT / asset)
    records = catalog()
    scopes = [("dev", None)] + [(r["version"], r) for r in records]
    current_sha = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    (ROOT / "IMPORT.md").write_text(import_document())
    for version, record in scopes:
        ref = record["docs_sha"] if record else None
        source_sha = record["source_sha"] if record else current_sha
        for lang in LABELS:
            for page in PAGES:
                text, fallback = localized(page, lang, ref)
                text = re.sub(
                    r"<!-- INSTALL:start -->[\s\S]*?<!-- INSTALL:end -->",
                    lambda _: installation(record, lang),
                    text,
                )
                text = re.sub(
                    r"<!-- LIVE:start -->[\s\S]*?<!-- LIVE:end -->",
                    lambda _: "```python\n" + read("examples/generate.py", ref) + "```",
                    text,
                )
                if "{{" in text:
                    raise ValueError(f"Unexpanded template: {page}")
                scope = (
                    (
                        f"{version} · "
                        + (
                            "Development/source documentation"
                            if lang == "en"
                            else "Documentación de desarrollo/código fuente"
                        )
                    )
                    if not record
                    else (f"PyPI {version} · source {source_sha[:12]} · docs {ref[:12]}")
                )
                notice = (
                    (
                        "Traducción ausente o desactualizada: se muestra el inglés "
                        "de esta misma versión."
                    )
                    if fallback
                    else ""
                )
                raw = f"> {scope}\n> {notice}\n\n" + transform_links(
                    text, version, lang, source_sha, True
                )
                write(f"agents/{lang}/{version}/{page}.md", raw)
                if version == "dev" and lang == "en":
                    write(f"agents/{page}.md", raw)
                body = markdown.markdown(
                    transform_links(text, version, lang, source_sha, False),
                    extensions=["fenced_code", "tables", "toc", "codehilite"],
                    extension_configs={"toc": {"permalink": "#"}},
                )
                nav = "".join(
                    f'<a href="{BASE}/{lang}/{version}/{p}/"'
                    + (' aria-current="page"' if p == page else "")
                    + f">{label}</a>"
                    for p, label in zip(PAGES, LABELS[lang])
                )
                versions = "".join(
                    f'<a href="{BASE}/{lang}/{v}/{page}/">{v}</a>' for v, _ in scopes
                )
                languages = "".join(
                    f'<a hreflang="{locale}" href="{BASE}/{locale}/{version}/{page}/">{name}</a>'
                    for locale, name in [("en", "English"), ("es", "Español")]
                )
                title = LABELS[lang][PAGES.index(page)]
                raw_url = f"{BASE}/agents/{lang}/{version}/{page}.md"
                output = f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} · TTS API Client · {version}</title>
<link rel="stylesheet" href="{BASE}/style.css"><link rel="canonical" href="https://lambdawalker.github.io{BASE}/{lang}/{version}/{page}/">
<link rel="alternate" hreflang="en" href="{BASE}/en/{version}/{page}/"><link rel="alternate" hreflang="es" href="{BASE}/es/{version}/{page}/">
</head><body><a class="skip" href="#main">{"Skip to content" if lang == "en" else "Ir al contenido"}</a>
<header><strong>TTS / API CLIENT</strong><a href="{BASE}/agents/{lang}/{version}/index.md">{"AI documentation" if lang == "en" else "Documentación para IA"}</a></header>
<div class="layout"><nav aria-label="{"Documentation" if lang == "en" else "Documentación"}">
<h2>{"Guides" if lang == "en" else "Guías"}</h2>{nav}<h2>{"Version" if lang == "en" else "Versión"}</h2>{versions}
<h2>{"Language" if lang == "en" else "Idioma"}</h2>{languages}
<h2>{"Maintainers" if lang == "en" else "Mantenimiento"}</h2><a href="{BASE}/maintainers/">{"Build and publish (English)" if lang == "en" else "Compilar y publicar (inglés)"}</a></nav>
<main id="main"><div class="scope">{html.escape(scope)}<br>{html.escape(notice)}</div>
<div lang="{"en" if fallback else lang}">{body}</div><footer><a href="{raw_url}">Markdown</a> · <a href="{REPO}/tree/{source_sha}">{source_sha[:12]}</a></footer></main></div>
<script src="{BASE}/copy.js" defer></script></body></html>'''
                write(f"{lang}/{version}/{page}/index.html", output)
    landing_version = records[-1]["version"] if records else "dev"
    write("index.html", (OUT / f"en/{landing_version}/index/index.html").read_text())
    write(
        "IMPORT.md",
        import_document().replace("(docs/agents/index.md)", f"({BASE}/agents/index.md)"),
    )
    write(
        "llms.txt",
        f"# TTS API Client\n\n- [Development agent entry]({BASE}/agents/index.md)\n"
        f"- [Installation]({BASE}/IMPORT.md)\n- [Version catalog]({BASE}/catalog.json)\n",
    )
    write("catalog.json", json.dumps({"development": "dev", "releases": records}, indent=2) + "\n")
    maintainers = "\n\n".join(
        (ROOT / p).read_text() for p in ["docs/documentation.md", "docs/publishing.md"]
    )
    write(
        "maintainers/index.html",
        '<!doctype html><html lang="en"><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f'<link rel="stylesheet" href="{BASE}/style.css"><title>Maintainers · TTS API Client</title>'
        f'<main><a href="{BASE}/en/dev/index/">Guides</a>'
        + markdown.markdown(maintainers, extensions=["fenced_code", "tables", "toc"])
        + "</main></html>",
    )
    check()


class Links(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []
        self.ids = set()

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if "id" in attrs:
            self.ids.add(attrs["id"])
        for field in ["href", "src"]:
            if field in attrs:
                self.links.append(attrs[field])


def check():
    if not OUT.exists():
        raise ValueError("Build the site first")
    for file in OUT.rglob("*"):
        if not file.is_file() or file.suffix not in {".html", ".md"}:
            continue
        text = file.read_text()
        parser = Links()
        if file.suffix == ".html":
            parser.feed(text)
            links = parser.links
        else:
            links = re.findall(r"\]\(([^)]+)\)", text)
        for link in links:
            url = urlsplit(link)
            if url.scheme or url.netloc:
                continue
            if url.path.startswith(BASE + "/"):
                target = OUT / unquote(url.path[len(BASE) + 1 :])
            elif url.path.startswith("/"):
                raise ValueError(f"Link escapes project base: {link}")
            else:
                target = file.parent / unquote(url.path) if url.path else file
            if target.is_dir():
                target = target / "index.html"
            if not target.is_file():
                raise ValueError(f"{file}: missing target {link}")
            if url.fragment:
                parsed = Links()
                if target.suffix == ".html":
                    parsed.feed(target.read_text())
                else:
                    parsed.feed(markdown.markdown(target.read_text(), extensions=["toc"]))
                if unquote(url.fragment) not in parsed.ids:
                    raise ValueError(f"Missing anchor {link}")
    print("Site links, anchors, raw Markdown and project base: OK")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["build", "check"])
    args = parser.parse_args()
    build() if args.command == "build" else check()
